//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Diplomas struct {
	DiplomaID             int32 `sql:"primary_key"`
	DiplomaUniversity     string
	DiplomaFaculty        *string
	DiplomaCurriculum     string
	DiplomaSpecialization *string
}
