//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type StudentCourses struct {
	CourseID  int32 `sql:"primary_key"`
	StudentID int32 `sql:"primary_key"`
}
