// Code generated by "enumer -type=PeriodType -json -transform=snake"; DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PeriodTypeName = "dayweekmonthyear"

var _PeriodTypeIndex = [...]uint8{0, 3, 7, 12, 16}

const _PeriodTypeLowerName = "dayweekmonthyear"

func (i PeriodType) String() string {
	i -= 1
	if i < 0 || i >= PeriodType(len(_PeriodTypeIndex)-1) {
		return fmt.Sprintf("PeriodType(%d)", i+1)
	}
	return _PeriodTypeName[_PeriodTypeIndex[i]:_PeriodTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PeriodTypeNoOp() {
	var x [1]struct{}
	_ = x[Day-(1)]
	_ = x[Week-(2)]
	_ = x[Month-(3)]
	_ = x[Year-(4)]
}

var _PeriodTypeValues = []PeriodType{Day, Week, Month, Year}

var _PeriodTypeNameToValueMap = map[string]PeriodType{
	_PeriodTypeName[0:3]:        Day,
	_PeriodTypeLowerName[0:3]:   Day,
	_PeriodTypeName[3:7]:        Week,
	_PeriodTypeLowerName[3:7]:   Week,
	_PeriodTypeName[7:12]:       Month,
	_PeriodTypeLowerName[7:12]:  Month,
	_PeriodTypeName[12:16]:      Year,
	_PeriodTypeLowerName[12:16]: Year,
}

var _PeriodTypeNames = []string{
	_PeriodTypeName[0:3],
	_PeriodTypeName[3:7],
	_PeriodTypeName[7:12],
	_PeriodTypeName[12:16],
}

// PeriodTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PeriodTypeString(s string) (PeriodType, error) {
	if val, ok := _PeriodTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PeriodTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PeriodType values", s)
}

// PeriodTypeValues returns all values of the enum
func PeriodTypeValues() []PeriodType {
	return _PeriodTypeValues
}

// PeriodTypeStrings returns a slice of all String values of the enum
func PeriodTypeStrings() []string {
	strs := make([]string, len(_PeriodTypeNames))
	copy(strs, _PeriodTypeNames)
	return strs
}

// IsAPeriodType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PeriodType) IsAPeriodType() bool {
	for _, v := range _PeriodTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PeriodType
func (i PeriodType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PeriodType
func (i *PeriodType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PeriodType should be a string, got %s", data)
	}

	var err error
	*i, err = PeriodTypeString(s)
	return err
}
