//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Courses = newCoursesTable("public", "courses", "")

type coursesTable struct {
	postgres.Table

	// Columns
	CourseID                postgres.ColumnInteger
	CourseName              postgres.ColumnString
	MonthlySubscriptionCost postgres.ColumnFloat

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CoursesTable struct {
	coursesTable

	EXCLUDED coursesTable
}

// AS creates new CoursesTable with assigned alias
func (a CoursesTable) AS(alias string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CoursesTable with assigned schema name
func (a CoursesTable) FromSchema(schemaName string) *CoursesTable {
	return newCoursesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CoursesTable with assigned table prefix
func (a CoursesTable) WithPrefix(prefix string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CoursesTable with assigned table suffix
func (a CoursesTable) WithSuffix(suffix string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCoursesTable(schemaName, tableName, alias string) *CoursesTable {
	return &CoursesTable{
		coursesTable: newCoursesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCoursesTableImpl("", "excluded", ""),
	}
}

func newCoursesTableImpl(schemaName, tableName, alias string) coursesTable {
	var (
		CourseIDColumn                = postgres.IntegerColumn("course_id")
		CourseNameColumn              = postgres.StringColumn("course_name")
		MonthlySubscriptionCostColumn = postgres.FloatColumn("monthly_subscription_cost")
		allColumns                    = postgres.ColumnList{CourseIDColumn, CourseNameColumn, MonthlySubscriptionCostColumn}
		mutableColumns                = postgres.ColumnList{CourseNameColumn, MonthlySubscriptionCostColumn}
	)

	return coursesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CourseID:                CourseIDColumn,
		CourseName:              CourseNameColumn,
		MonthlySubscriptionCost: MonthlySubscriptionCostColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
