env: "dev"

http_server:
  address: "127.0.0.1:8082"
  timeout: 4s
  idle_timeout: 30s
  shutdown_timeout: 10s

logger:
  level: "debug"
  encoding: "console"

auth:
  access_token_ttl: 2h
  refresh_token_ttl: 720h

redis:
  addr: "localhost:6379"

rabbit_mq:
  host: "localhost"
  port: 5672
  notification_publisher:
    exchange: ""
  notification_consumer:
    name: "notification"
    queue: "notification"

notify:
  email_provider:
    from: "dussh@school.com"
