env: "dev"
storage_path: "./storage.db"

http_server:
  address: "127.0.0.1:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"
  password: "24tf02f4jrf"
  shutdown_timeout: 10s

logger:
  level: "debug"
  encoding: "console"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "hnope171512mro"
  db_name: "dussh"

auth:
  secret_key: "advadmippin428nfg482n"
  access_token_ttl: 2h
  refresh_token_ttl: 720h

redis:
  addr: "localhost:6379"
  password: "E/Ru5KgRNeKGVJUEnrWDqAk+/We3dSft9NrqdCM9ya1+t9zpFTBiY4Njmj8yZOxIjt9+w8lxXH9N9pUu"